### ISSUE TITLE
[transfer-hw-to-cert] The transfer location cannot run with Rack number

### ISSUE THREAD

**Issue by clairlin53** [canonical/oem-qa-tools#62]
If the location set with R01, and it will return error

CID:202110-27997
Location:TEL-L3-R01-S10-P0

error code:
```
-----Updating Cert Lab Google Sheet-----
current api type: service-account
INFO  - __init__  : autodetect 49   - file_cache is only supported with oauth2client<4.0.0
Traceback (most recent call last):
  File "/home/clair/Documents/OEM-QA/20240110/oem-qa-tools/Tools/PC/transfer-hw-to-cert/main.py", line 113, in <module>
    main()
  File "/home/clair/Documents/OEM-QA/20240110/oem-qa-tools/Tools/PC/transfer-hw-to-cert/main.py", line 73, in main
    update_cert_lab_google_sheet(data['data'])
  File "/home/clair/Documents/OEM-QA/20240110/oem-qa-tools/Tools/PC/transfer-hw-to-cert/handlers/cert_team_google_sheet_handler.py", line 283, in update_cert_lab_google_sheet
    empty, non_empty_list = are_candidated_sheet_cells_empty(
  File "/home/clair/Documents/OEM-QA/20240110/oem-qa-tools/Tools/PC/transfer-hw-to-cert/handlers/cert_team_google_sheet_handler.py", line 179, in are_candidated_sheet_cells_empty
    raise Exception(f"Error: Lab \'{lab}\' is not in indexed table")
Exception: Error: Lab 'None' is not in indexed table
```

**Comment by clairlin53** [comment]
Fixed by https://github.com/canonical/oem-qa-tools/pull/63
